#!/bin/sh
#
# List AWS organization accounts
#
# 20221230  Kimmo Suominen
#
###############################################################################
#
# Copyright (c) 2022-2024 Kimmo Suominen
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer
#    in the documentation and/or other materials provided with the
#    distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
###############################################################################

set -eu

PATH="${HOME}/bin/share:${HOME}/.local/bin"
PATH="${PATH}":/usr/local/bin:/opt/local/bin:/usr/pkg/bin:/bin:/usr/bin
export PATH

PROG="${0##*/}"

AWS_DEFAULT_OUTPUT=json
export AWS_DEFAULT_OUTPUT

die()
{
    echo "${PROG}: ${@}" 1>&2
    exit 1
}

usage()
{
    cat <<EOF
Usage:	env AWS_PROFILE=profile ${PROG}

List member accounts of the organization.
EOF
}

if [ ${#} -ne 0 ]
then
    usage 1>&2
    exit 1
fi

aws organizations list-accounts \
| jq -r '
    .Accounts
    | map({
	"id": .Id,
	"name": .Name,
	"status": .Status,
	"how": .JoinedMethod,
	"when":
	  .JoinedTimestamp
	  | sub("\\.\\d+"; "")
	  | strptime("%Y-%m-%dT%H:%M:%S%Z")
	  | strflocaltime("%F %T %Z")
    })
    | sort_by(.when)
    | map(join(","))
    | .[]
' \
| sed '1 i\
ID,NAME,STATUS,HOW,WHEN
' \
| column -s, -t
